/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

plugins {
  // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
  `kotlin-dsl`
}

repositories {
  mavenCentral()
  // Use the plugin portal to apply community plugins in convention plugins.
  gradlePluginPortal()
  ampereApiGithub()
}

fun RepositoryHandler.ampereApiGithub(): MavenArtifactRepository = maven {
  url = uri("https://maven.pkg.github.com/Ampere-Mod/api")
  credentials {
    username = System.getenv("GITHUB_ACTOR")
    password = System.getenv("GITHUB_TOKEN")
  }
}

// https://plugins.gradle.org/plugin/net.neoforged.moddev
dependencies {
  implementation("net.neoforged.moddev:net.neoforged.moddev.gradle.plugin:2.0.80")
  implementation("org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:2.1.20")
  implementation("com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:9.0.0-beta12")
}

//sourceSets.main.get().java.srcDir("../settings/src/main/kotlin")

tasks.named<Wrapper>("wrapper") {
  distributionType = Wrapper.DistributionType.BIN
}

tasks.withType<JavaCompile>().configureEach {
  options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}
