/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

plugins {
  // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
  `kotlin-dsl`
}

repositories {
  // Use the plugin portal to apply community plugins in convention plugins.
  gradlePluginPortal()
}

// https://plugins.gradle.org/plugin/net.neoforged.moddev
dependencies {
  implementation("net.neoforged.moddev:net.neoforged.moddev.gradle.plugin:2.0.80")
}

tasks.named<Wrapper>("wrapper") {
  distributionType = Wrapper.DistributionType.BIN
}

tasks.withType<JavaCompile>().configureEach {
  options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}
